### ISSUE TITLE
Can't find the effect.

### ISSUE THREAD

**Issue by HawtinZeng** [astoilkov/main-thread-scheduling#11]
I have entered the link, [this CodeSandbox](https://codesandbox.io/s/main-thread-scheduling-example-qqef6?file=/src/App.js:1188-1361), can't find any difference between un-commented and commented code..Maybe my PC is powerful enought to handle the heavy task...Do u want to use some tools to test your improvements, such as tinybench?

**Comment by astoilkov** [comment]
I've updated the example sandbox. Can you try again?

Do you have ideas on how it can be done with tinybench? The problem I see is that `main-thread-scheduling` is trying to make the user experience smooth without freezing the UI but it actually increases the total time it takes for the function to execute because it gives back control to other code to execute as well.

**Comment by HawtinZeng** [comment]
The example is great, I can see the input element is freezed when I input character.Maybe we can record the time interval from pressing keyboard to triggering change or input event of input element, when I commented yieldOrContinue, I found the input change can't catch up with the speed of pressing keyboard, look this gif, after pressing keyboard many times, the change event still don't stop.At the time when I moved the cursor, I had already stop pressing keyboard.But this freezing is very easy to perceive, there is no need to calculate the time interval.

**Comment by astoilkov** [comment]
I can't see the gif, maybe it wasn't uploaded. I might also add the time between updates at some point as well, I like the idea.

I'm happy you now see the difference. I'm closing this issue then. If you have any more feedback, I'm here. Thanks for the idea for the improvement!
