### ISSUE TITLE
Safari  Not Supported requestIdleCallback Can it still be used normally?

### ISSUE THREAD

**Issue by MoNaiZi** [astoilkov/main-thread-scheduling#16]

**Comment by astoilkov** [comment]
`requestIdleCallback` is available in Safari Technology Preview so full support is coming as well. 

In the meantime, the difference in behavior you get in Safari is — because `navigator.scheduling.isInputPending()` isn't available the execution of your code won't stop immediately after the user starts typing, clicking, or another user action, but will complete it's time (a few milliseconds more) and then return to executing other code.
